### ISSUE TITLE
Cannot create user without passing DesiredDeliveryMediums even tough it's optional

### ISSUE THREAD

**Issue by fabio-andre-rodrigues** [jagregory/cognito-local#274]
According to amazon cognito documentation about [AdminCreaterUser#DesiredDeliveryMediums](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html#API_AdminCreateUser_RequestSyntax) this parameter is optional (due to have a default of ["SMS"] ) and indeed if we send a request without that for Amazon Cognito a user is created. Also we didn't send the message by setting the MessageAction  to SUPRESS in the request:

```
 var request = new AdminCreateUserRequest {
                Username = userProfile.Id.ToString(),
                UserPoolId = config.PoolId,
                UserAttributes = SetUserAttributes(userProfile),
                MessageAction = "SUPPRESS",
                TemporaryPassword = password,
            };
```

But when using cognito-local for testing, the same request will fail due to a :

```[1658407997167] WARN: e23e29db NONE Error handling target: AdminCreateUser {"reqId":"e23e29db"}
    err: {
      "type": "InvalidParameterError",
      "message": "User has no attribute matching desired delivery mediums",
      "stack":
          Error: User has no attribute matching desired delivery mediums
              at deliverWelcomeMessage (/app/start.js:1273396:11)
              at /app/start.js:1273434:9
              at async /app/start.js:1274726:17
      "code": "CognitoLocal#InvalidParameterException"
    }```

**Comment by fabio-andre-rodrigues** [comment]
ah found that the  MessageAction = "SUPPRESS" is not yet developed
